### ISSUE TITLE
One of the parameter types of function RWKV may be wrong

### ISSUE THREAD

**Issue by yuyi2439** [harrisonvanderbyl/rwkvstic#23]
First of all, my English is not very good, please forgive me.
The type of the `mode` parameter for [this](https://github.com/harrisonvanderbyl/rwkvstic/blob/55826c8d0bdf89ba36bc4eb6518fa736aa479913/src/rwkvstic/load.py#L18C104-L18C104) line.
I think it may be `Union`, because it conflicts with the example in the README.

**Comment by harrisonvanderbyl** [comment]
I think you are correct, good spot!

**Comment by yuyi2439** [comment]
> I think you are correct, good spot!

ok, thank you
