### ISSUE TITLE
when i load 14b ,this happened.

### ISSUE THREAD

**Issue by xiaol** [harrisonvanderbyl/rwkvstic#9]
![MT)RY8JG}_ACY92)91RS%7S](https://user-images.githubusercontent.com/1669515/220097544-fdd93244-3585-4732-baa0-397e4ced599b.png)
![image](https://user-images.githubusercontent.com/1669515/220097809-dfd31747-df40-4e15-a32f-37f7442c985b.png)

**Comment by harrisonvanderbyl** [comment]
better on 0.3.3
